#Fields and Flows
In this chapter, we consider equations whose iterates move gradually rather than abruptly from one place to another. Such equations are called differential equations, and they are the basis for most dynamical systems that describe natural processes. The programming is a simple extension of what we have done before, but the calculation requires more computing time. The attractors produced by differential equations consist of continuous lines whose weavings and waverings describe the trajectory and yield objects of considerable beauty.


## Beam Me up Scotty!
	Successive iterates of the maps in the previous chapters are usually at widely different positions on the attractors. The points dance around like fleas jumping on the back of a dog, eventually, but gradually, visiting every allowed location. Most processes in nature don’t occur that way but progress slowly and continuously from some initial condition through a succession of nearby intermediate states to the final condition.
	If you take a trip across the country, your trajectory through three-dimensional space (or even in four-dimensional space-time) is a continuous one-dimensional curve. Only in science fiction is Captain Kirk able to dematerialize at one position and rematerialize somewhere else, without occupying a succession of intermediate positions. Most substances in nature obey a continuity equation, which guarantees that if their quantity decreases at some position, the decrease must be accompanied by a flow of the substance away from the position. Note that this is a stronger condition than a conservation law, which requires only that the total quantity of the substance remains the same.
	There is a relation between flows and maps. Imagine a fly trapped in a room and moving in a complicated, random manner. Its trajectory is a one-dimensional curve that eventually fills the entire room. However, if you observe the fly with a strobe lamp that flashes periodically, the trajectory is a succession of dots, with each dot separated from the previous dot by a significant distance. The dots also eventually fill the entire three-dimensional region, but it takes longer for this to occur.
	However, if the fly’s motion is chaotic rather than random, neither the curve nor the dots fill the room; rather, they lie on a strange attractor that occupies a negligible portion of the room. The attractor consisting of all the possible dots often has a lower dimension than the attractor consisting of all the possible curves. Thus a map can be thought of as a crude description of a flow, in which the intervening details of the motion are ignored.
	It’s easy to think of an object such as a fly or a human, imbued with intelligence, however limited, moving by free will along a complicated trajectory. However, inanimate objects, such as astronomical bodies or sub-microscopic, electrically charged particles, can also execute complicated motions. They do so because they move through a space filled with gravitational or electromagnetic fields.
	It is important to recognize that a field has no objective reality other than to describe mathematically the force on an object moving through it. When something is dropped, it falls toward Earth. It is a deeply philosophical question, not answered very well by science, how the object knows to move toward Earth rather than in some other direction. We say that it is acted upon by the gravitational field of the Earth, but this description, however useful for calculating the motion, begs the issue. Ultimately, the laws of physics describe very accurately how things move, but not very well why.
	The equations that describe flows are of a different type than those that describe maps. They are called differential equations, and they involve the rate of change of a quantity. We will consider only ordinary differential equations (ODEs), as distinguished from the partial differential equations (PDEs) used to describe the behavior of complicated objects like fluids that have intrinsically infinite-dimensional state spaces. Dynamical systems described by ODEs involve only the time rate of change of the position of a point in state space, whereas with PDEs, the variables are quantities like density, temperature, and electric field that change in space as well as time. A wave is an example of a dynamical system described by a PDE.
	Consider an object moving in the X direction. Its speed is the rate of change of its position, and we will denote this quantity by X’ (pronounced “X prime”). It is the distance the object moves in a brief interval of time divided by the time interval. If you know some calculus, you recognize this as the time-derivative of X, usually denoted by dX/dt. The rate of change of position is what the speedometer on your car, or the police radar, reads. The rate of change of the speed is the acceleration. More properly, we should call these quantities the time rate of change, since quantities can also change in space. For example, the spatial rate of change in altitude of a road is called its grade.
	An object moving in three-dimensional space has a constantly changing value not only of X but also of Y and Z. Furthermore, X’, Y’, and Z’ usually depend on position (X, Y, and Z). For example, a particle moving clockwise in a circle about the origin in the XY plane is described by the following pair of differential equations:

	X’ = Y
	Y’ = -X							(Equation 6A)

Such a set of equations describes, at least approximately, the motion of the earth around the sun. This type of regular motion is not chaotic, and it does not lead to visually interesting strange attractors.
	Some differential equations can be solved easily using calculus. For example, Equation 6A has the solution

	X = A sin(t + f)
	Y = A cos(t + f)					(Equation 6B)

which specifies the X and Y positions at any time t. The quantities A and  are constants that are determined from the initial conditions (the values of X and Y at t = 0). If you are interested only in the shape of the trajectory, and not in where the object is along it at any particular time, you can eliminate the t in Equations 6B to get a relation between X and Y,

	X2 + Y2 = A2     	               (Equation 6C)

which is the equation for a circle of radius A centered on the origin (X = Y = 0).
	Equation 6A also arises in a different context. Imagine an object moving back and forth in the X direction, perhaps attached to a spring that alternately stretches and compresses. Since Y is equal to X’, we can associate Y with the velocity in the X direction. The XY plane then becomes the two-dimensional phase space for this one-dimensional motion, and the trajectory in this plane is the phase-space trajectory. A circular phase-space trajectory is a characteristic of a one-dimensional, simple harmonic oscillator, such as a mass on a spring. Usually the phase-space trajectory is an ellipse, just as the orbit of the earth around the sun is an ellipse, but we can always measure Y in appropriate units, or adjust the scale of the graph, to change the ellipse into a circle.
	With this interpretation, the first part of Equation 6A defines the velocity (Y) as the rate of change of position (X’). If you remember your physics, the second part of Equation 6A is Newton’s second law (F = ma), in which the force F obeys Hooke’s law for springs (F = - kX), and the acceleration a is the rate of change of velocity (Y’). It is interesting that the same set of differential equations with a change in the meaning of the variables can describe the motion of an object traveling in a circle or an object oscillating on the end of a spring. Equation 6A describes many other phenomena in nature, such as the oscillations in an electrical circuit containing a capacitor and inductor.
	A two-dimensional system of differential equations such as Equation 6A cannot exhibit chaos, according to the Poincaré-Bendixon theorem, because the trajectory cannot cross itself. The most complicated bounded behavior is thus a simple closed loop, corresponding to periodic motion. The reason the trajectory cannot cross itself is that every point in the XY plane has associated with it a unique direction of flow, so the trajectory must approach and leave every point in a single particular  direction. If the orbit were to return to a point previously visited, it would thereafter repeat what it did before. In two dimensions, the orbit can do only one of three things: spiral into a fixed point, approach a stable limit cycle, or spiral off to infinity.
	Trajectories may appear to cross if they come very close to a fixed point that is stable in one direction and unstable in another (called a saddle point or X point because of its shape). Such a trajectory is called a separatrix because it separates regions with different flows. Trajectories approaching the fixed point on one side of the separatrix veer off to the right, and those approaching from the other side veer off to the left. Such a separatrix exists upstream (and downstream) of an island in a river where two sticks placed side by side in the water end up going around opposite sides of the island. The island seems at first to attract the sticks and then to repel them at right angles as they approach it.
	In three dimensions, we have the possibility of an orbit wrapping around in a complicated manner, like a ball of string, never intersecting itself, but producing a never-ending tangle. By contrast, maps can be chaotic in one or two dimensions because the points jump from place to place with little danger of intersecting another point. Captain Kirk need not be concerned about a collision while being transported from one point to another. He only needs to worry about landing on top of a diabolical Romulan at his destination!


##  Professor Lorenz and Dr. Rössler
	Although differential equations have been the mathematical basis for most descriptions of nature for hundreds of years, almost no one suspected that the trajectories resulting from their solution could be a chaotic strange attractor. The history of the discovery of such solutions is interesting and bears retelling.
	In the early 1960s, Edward Lorenz, a meteorologist at the Massachusetts Institute of Technology, was developing models of atmospheric convection to be solved by a primitive computer that required about one second per iteration. His models involved a large number of differential equations and produced solutions that varied with time in a complicated manner, not unlike the variation of the weather over long intervals of time. On one occasion, he happened to restart one of his computer runs using numbers rounded to three digits rather than the six significant figures used by the computer.
	For some time, the solutions followed one another, but after a while they began to depart, and eventually they bore no relation to one another. He had discovered the sensitivity to initial conditions that is perhaps the most salient feature of chaos. He began simplifying his equations in an attempt to determine the minimum conditions necessary for this bizarre behavior. The result is the now famous Lorenz equations, which represent the first example of a strange attractor arising from differential equations,

	X’ = s(Y - X)
	Y’ = -XZ + rX - Y
	Z’ = XY - bZ						(Equation 6D)

where , r, and b are constants that Lorenz took to be  = 10, r = 28, and b = 8/3. Lorenz published his findings in 1963 in the Journal of the Atmospheric Sciences, where they went largely unnoticed for the next decade. The title of his paper, “Deterministic Nonperiodic Flow,” is an apt description of what we now call chaos.
	Although the Lorenz equations were distilled from a model of atmospheric convection, the trajectory in XYZ space does not represent air currents in any literal way. Instead, X corresponds to the size of the convective motion, Y is proportional to the temperature difference between the ascending and descending fluids, and Z is proportional to the deviation of the vertical temperature profile from a linear function. Nevertheless, the behavior is reminiscent of a fluid with turbulent convection.
	Since the Lorenz equations were proposed, several phenomena have been found that are at least approximately modeled by them. Perhaps the simplest example is the thermosiphon. Imagine a continuous tube, like a bicycle tube, filled with a liquid and mounted vertically. If the bottom of the tube is heated and the top cooled, a convection ensues, with the warm fluid rising and the cold fluid falling. The convection is equally likely to start in either direction. After it starts, the circulation continues in that direction a few times around the loop and then abruptly reverses.
	In the 1970s other examples of chaotic differential equations began to be discovered. An important contribution was made in 1976 by Otto Rössler, a nonpracticing medical doctor in Germany. Rössler was interested in chaos in chemistry and theoretical biology, and he set about to find a system of equations even simpler than those of Lorenz that exhibited chaotic behavior. What he came up with are the now famous Rössler equations:

	X’ = -(Y + Z)
	Y’ = X + aY
	Z’ = b + Z(X - c)					(Equation 6E)

where a, b, and c are constants that Rössler took to be a = 0.2, b = 0.2, and c = 5.7. The Rössler equations are sometimes described as the simplest known example of chaos arising from a system of ordinary differential equations. They contain a single nonlinearity (ZX in the third equation). Rössler’s original paper is also interesting because it contains a stereoscopic view of his strange attractor as well as the Lorenz attractor.
	Until very recently, the discovery of a new strange attractor was a cause to rush to publication. With the program in this book, you can produce them by the thousands! Even today researchers tend to focus on a few well-known examples such as the Lorenz and Rössler attractors. An entire book has been written on the Lorenz attractor alone. Think of the libraries that could be filled by books describing your attractors in similar detail!
	The Lorenz and Rössler attractors are shown in Figures 6-1 and 6-2, respectively, albeit with slightly different values of the parameters than they used. These cases are known to have fractal dimensions slightly greater than 2.0. These examples are more important for their historical interest than for their visual appeal. If you have never seen these attractors in 3-D, be sure to return to these cases and view them with the various display techniques after the program has been appropriately modified, as described in the next section. The Lorenz attractor resembles the wings of a butterfly, making it an appropriate emblem of chaos, since the sensitivity to initial conditions is most dramatically illustrated by the butterfly effect.

Figure 6-1. The Lorenz attractor

Figure 6-2. The Rössler attractor


## Finite Differences
	Some differential equations, such as Equation 6A, can be solved exactly in a straightforward manner using calculus. However, if a system of equations exhibits chaos, no such solution is possible. The reason is that no mathematical function analogous to the sine and cosine can describe a strange attractor the way those functions describe a circle. The equations must be solved by computer. We say that such solutions are numerical as opposed to analytical.
	Unfortunately, digital computers, which are ideal for iterating maps, are inherently incapable of exactly solving differential equations. The equations require that the solution advance slowly and smoothly. That is, the successive iterates must differ by an infinitesimal amount, thus infinitely many iterations are required to make any progress. Special analog computers have been designed for the task, but they are not common or simple to program.
	Books have been written on methods for the approximate numerical solution of differential equations, and it is as much an art as a science. All the methods involve, in one form or another, a finite-difference approximation to the differential equation. Rather than taking infinitesimal steps, one advances in finite steps according to a prescription that attempts to minimize the inevitable errors. Fortunately, for our purpose, our solutions need not be highly accurate, so we can use a simple procedure.
	Perhaps the easiest and most transparent method for finding approximate solutions to differential equations is the Euler method. When this procedure is applied to the simple example of Equation 6A, X and Y are advanced according to

	Xn+1 = Xn + eYn
	Yn+1 = Yn - eXn						(Equation 6F)

where  is the time step that ideally should be negligibly small but in reality is made as large as possible to reduce the number of iterations required to advance the solution by a substantial distance along the trajectory. You see that the Euler method provides just another example of an iterated map in which successive iterates are near one another. It is perhaps the least accurate method for solving differential equations, and it is easily improved upon. However, for most of our purposes, the Euler method is adequate. Furthermore, it is simple to modify the program to solve differential equations by this method. The necessary changes are shown in PROG21.

PROG21. Changes required in PROG20 to solve differential equations by the Euler method
1000 REM ODE SEARCH
1070 D% = 3                     'Dimension of system
1080 EPS = .1                   'Step size for ODE
1090 ODE% = 1                   'System is ODE

1990 IF ODE% = 1 THEN XN(I%) = XY(I%) + EPS * XN(I%)

2660    CODE$ = CHR$(59 + 4 * D% + O% + 8 * ODE%)

3050    IF ODE% = 1 THEN L = L / EPS

3660 IF ODE% = 1 THEN D% = D% + 2
3680 IF Q$ = "D" THEN D% = 1 + (D% MOD 6): T% = 1
3700 IF D% > 4 THEN ODE% = 1: D% = D% - 2 ELSE ODE% = 0

4300    PRINT TAB(27); "D: System is"; STR$(D%); "-D polynomial ";
4310    IF ODE% = 1 THEN PRINT "ODE" ELSE PRINT "map"

4730 IF D% > 4 THEN D% = D% - 2: ODE% = 1 ELSE ODE% = 0
	In PROG21, the value of  is 0.1, and the three-dimensional equations are polynomials up to fifth order, with coefficients chosen by analogy to the three-dimensional polynomial maps previously described. We don’t consider differential equations in less than three dimensions because they cannot have chaotic solutions. The second-order through fifth-order equations are coded with the first letters Q, R, S, and T, respectively.
	If  is sufficiently small, its value should not affect whether a system is chaotic or the general appearance of the attractor, but it certainly changes the trajectory on the attractor. Just as a chaotic trajectory is sensitive to initial conditions, it also is sensitive to the approximations used to calculate it. Unfortunately, a value of  = 0.1 is not sufficiently small, and many of the resulting attractors would disappear or change their appearance if  were reduced. Conversely, other attractors would emerge for smaller values of . Fortunately, for our purposes, the solutions need not be even qualitatively correct. Be forewarned that reducing  has unpredictable effects on the attractors and increases the computation time.
	The Lyapunov exponent is calculated as with the corresponding maps, except that it is divided by ; thus its units are bits per second rather than bits per iteration, because each iteration advances the solution by  seconds. It is customary to express the Lyapunov exponent in this way for differential equations because the step size depends on the numerical approximation that is being used, whereas the divergence of the trajectories per unit time is an intrinsic property of the differential equations.
	Sample attractors produced by three-dimensional ordinary differential equations projected onto the XY plane are shown in Figures 6-3 through 6-6.

Figure 6-3. Projection of three-dimensional quadratic ODE

Figure 6-4. Projection of three-dimensional cubic ODE

Figure 6-5. Projection of three-dimensional quartic ODE

Figure 6-6. Projection of three-dimensional quintic ODE

	These figures are like time-exposed photographs of the shadow on the wall of a fly moving chaotically in a room. However, because of the finite difference approximation used to solve the equation of motion, you must imagine that the fly is illuminated by a strobe lamp that flashes rapidly. The trajectory thus consists of a large number of closely spaced dots. The separation of the dots provides a measure of the accuracy of the solution. Although some of the cases produce apparently continuous trajectories, others more nearly resemble the maps of the previous chapters. You might prefer to alter the program so that the dots are connected by lines. This is most easily done by changing line 5060 to 

5060 IFTRD% = Ø THEN IFODE% = 1 THEN
LINE-(XP, YP), C4% ELSEPSET(XP, YP), C4%

	Another consequence of dealing with differential equations is that many iterations are required for the solution to settle onto the attractor. Since we use the same criterion for the number of iterations as we did for the maps, a significant number (perhaps 20%) of the attractors found in a random search are not chaotic, and a few are even unbounded. When you evaluate the attractors found by the search, you will recognize these cases by the way they eventually settle onto a simple closed loop that is visually indistinguishable from a limit cycle, spiral into a fixed point, or leave the screen. You will also notice a few cases that consist of isolated islands with no bridge connecting them, such as the one in Figure 6-3. You can be sure these are not true flows, because such discontinuities are impossible in the trajectories that arise from the solution of our differential equations.
	There is no reason to limit the display of attractors arising from differential equations to projections onto a plane. All the display techniques developed in Chapter 4 for three-dimensional maps are also available here. Figures 6-7 through 6-22 and Plates 23 and 24 show a selection of such examples.

Figure 6-7. Three-dimensional quadratic ODE with shadows

Figure 6-8. Three-dimensional cubic ODE with shadows

Figure 6-9. Three-dimensional quartic ODE with shadows

Figure 6-10. Three-dimensional quintic ODE with shadows

Figure 6-11. Three-dimensional quadratic ODE with contour bands

Figure 6-12. Three-dimensional cubic ODE with contour bands

Figure 6-13. Three-dimensional quartic ODE with contour bands

Figure 6-14. Three-dimensional quintic ODE with contour bands

Figure 6-15. Stereo pair of three-dimensional quadratic ODE

Figure 6-16. Stereo pair of three-dimensional cubic ODE

Figure 6-17. Stereo pair of three-dimensional quartic ODEFigure 6-18. Stereo pair of three-dimensional quintic ODE

Figure 6-19. Slices of a three-dimensional quadratic ODE

Figure 6-20. Slices of a three-dimensional cubic ODE

Figure 6-21. Slices of a three-dimensional quartic ODE

Figure 6-22. Slices of a three-dimensional quintic ODE

##  Flows in Four Dimensions
	Flows, like maps, can be embedded in spaces of arbitrary dimension. Four-dimensional flows are hard to visualize but pose no difficulty for the computer to calculate. Buried in PROG21 is the capability for calculating four-dimensional flows. You only need to press the D key to access the four-dimensional ODEs. All the techniques previously developed for displaying four-dimensional maps are available. The quadratic, cubic, quartic, and quintic equations are coded with the first letters U, V, W, and X, respectively. Figures 6-23 through 6-38 and Plates 25 through 30 show a selection of strange attractors arising from four-dimensional ordinary differential equations with polynomial terms.

Figure 6-23. Projection of a four-dimensional quadratic ODE

Figure 6-24. Projection of a four-dimensional cubic ODE

Figure 6-25. Projection of a four-dimensional quartic ODE

Figure 6-26. Projection of a four-dimensional quintic ODE

Figure 6-27. Four-dimensional quadratic ODE with shadow bands

Figure 6-28. Four-dimensional cubic ODE with shadow bands

Figure 6-29. Four-dimensional quartic ODE with shadow bands

Figure 6-30. Four-dimensional quintic ODE with shadow bands

Figure 6-31. Four-dimensional quadratic ODE with stereo bands

Figure 6-32. Four-dimensional cubic ODE with stereo bands

Figure 6-33. Four-dimensional quartic ODE with stereo bands

Figure 6-34. Four-dimensional quintic ODE with stereo bands

Figure 6-35. Four-dimensional quadratic ODE with sliced bands

Figure 6-36. Four-dimensional cubic ODE with sliced bands

Figure 6-37. Four-dimensional quartic ODE with sliced bands

Figure 6-38. Four-dimensional quintic ODE with sliced bands


## Strange Attractors that Aren’t
	In Section 3.8, we discussed chaotic orbits that don’t approach an attractor (“Strange Attractors that Don’t”). Here we consider nonchaotic orbits that approach attractors that aren’t strange. These attractors are not fractals. They have dimensions that are integers such as 0, 1, 2, or 3. Some of them are beautiful, so they are worth displaying even if they are technically outside the scope of this book.
	Such attractors can arise from maps as well as from differential equations. They don’t require high embedding dimensions, although the dimension of the attractor always is at least one less than the dimension of the embedding space. Thus some of the examples are taken from equations described in earlier chapters.
	The simplest nonchaotic attractor is a point attractor. Suppose we modified Equation 6A so the solution is not a circle but an inward spiral. One way to do this is as follows:

	X’ = Y - bX
	Y’ = -X - bY						(Equation 6G)

You can think of the coefficient b as a measure of the friction that eventually brings the trajectory to rest at the origin (X = Y = 0) in phase space. If b is zero (frictionless), the orbit is a circle. Negative values of b (antifriction) cause the solution to spiral outward, approaching infinity. This case corresponds to a point repellor at the origin. An attractive fixed point is called a sink and a repelling fixed point is called a source. Some authors reserve the term fixed point for maps and prefer to call the stationary solutions of ODEs critical points or equilibrium points.
	The two occurrences of b in Equation 6G need not have the same value or even the same sign. In such a case, the orbit moves in or out but not in a symmetrical manner. Many physical processes have b = 0 in one of the equations. If b is close to zero, it doesn’t matter much in which equation it appears.
	If b is zero in one of the equations above, small positive values of the other b cause the radius of the circle to decrease slowly, approaching what is called a spiral-point or focal-point attractor, or simply a focus. Larger positive values of b cause the radius to decrease more rapidly. With very large values of b, there is little circulation around the point, and the trajectory is more nearly radial toward what is called a radial-point or nodal-point attractor, or simply a node. The boundary between the two cases occurs at b = 2 and corresponds to critical damping in an oscillator. In either case, the resulting attractor is a point at the origin with a dimension of zero. A code that produces a point attractor (with b = 1) is QMLM3NM5LM3LM14. For this case, the largest Lyapunov exponent is negative (L = - 0.1/ln 2 = - 0.14), and it produces a single dot on the screen. 
	More interesting cases can occur because the program assumes the trajectory is on the attractor after 1000 iterations. For trajectories that approach the attractor very slowly, there can be interesting behavior after the thousandth iteration and before the fixed point is reached. Such slowly attracting fixed points have negative Lyapunov exponents, at least one of which is very close to zero. The search can be expanded to include them as well as other nonchaotic attractors by changing the .005 in line 2480 of the program to -.005, for example. Then attractors that have Lyapunov exponents near zero but have not settled to a fixed point after NMAX iterations are included in the file SA.DIC. If you prefer, you can collect them in a separate file TORUS.DIC by changing line 4910 of PROG21 to

4910 IF L > .005 THEN OPEN "SA.DIC" FOR APPEND AS #1 ELSE OPEN "TORUS.DIC" FOR APPEND AS #1

	Several such cases are shown in Figures 6-39 through 6-42. Figure 6-39 shows a spiral-point attractor. Figure 6-40 shows what appears to be a radial-point attractor with several different initial conditions; it is really a spiral-point attractor with successive iterates that move rapidly around the fixed point. This phenomenon is called aliasing, and it is most easily detected by connecting temporally successive points with continuous lines. Figures 6-41 and 6-42 show cases where the rate of circulation around the fixed point changes significantly as the fixed point is approached.

Figure 6-39. Trajectory approaching a spiral-point attractor

Figure 6-40. Trajectory emulating a radial-point attractor

Figure 6-41. Trajectory approaching a point attractor

Figure 6-42. Trajectory approaching a point attractor

	The point attractor is the simplest type of nonchaotic attractor. It has a dimension of zero. An attractor can also have a dimension of one, which is a line. Such attractors are limit cycles. They correspond to systems that settle into a periodic or cyclic behavior. Consequently, such attractors are also called cyclic attractors.
	The simplest differential equations that produce a cyclic trajectory are the equations in Equation 6A. The resulting orbit is a circle in the XY plane. This case is not an attractor, however, because every initial condition produces a circular trajectory whose radius is the distance of the initial point from the origin. There is no unique circle to which nearby orbits are attracted, and there is no basin of attraction. Furthermore, if you attempt to display the trajectory using a code such as QM5NM5LM18, you will find that the orbit is unbounded and spirals outward as if there were a point repellor at the origin. The reason is that our iteration scheme for approximating the solution of the differential equations is not exact. The errors compound and eventually cause the orbit to be lost.
	The simple undamped (frictionless) oscillator is said to be structurally unstable because an arbitrarily small perturbation to the equation (such as using the Euler finite difference approximation of Equation 6F) changes the structure of the solution from a closed loop to a never-ending spiral. Note the distinction between an unstable equation, in which a small modification of the equation causes a large change in the solution, and an unstable solution, in which a small variation of the initial condition away from the equilibrium value causes the solution to move ever farther from equilibrium.
	To produce a true limit cycle that is structurally stable, we need a system of equations whose solutions spiral outward from initial conditions in the interior and spiral inward from initial conditions on the exterior of the attractor. A suitable set of such equations is the following:

	X’ = Y + (1 - X2 - Y2)X
	Y’ = -X + (1 - X2 - Y2)Y				(Equation 6H)

The quantity (1 - X2 - Y2) plays the role of -b in Equation 6G. Whenever the trajectory lies inside the circle of radius one, it spirals outward, and whenever it lies outside the circle of radius one, it spirals inward. Thus the limit cycle is defined by the circle X2 + Y2 = 1. There is a point repellor at the origin, and the basin of attraction is the entire XY plane. A code that produces such a stable limit cycle, except with a smaller radius is RMNMAM3AM3NM9LM2AM6NMAM26.
	A limit cycle may be either stable or unstable, just like a fixed point. With an unstable limit cycle, nearby orbits move progressively farther from the limit cycle. An unstable limit cycle can be identified in an invertable map or system of ordinary differential equations by running time backwards, in which case the limit cycle becomes stable and attracts rather than repels nearby orbits.
	A slightly simpler version of Equation 6H that produces a stable limit cycle, although not a symmetrical one, is the following:

	X’ = Y
	Y’ = -X + (1 - X2)Y					(Equation 6I)

This system is called the Van der Pol equation, and it was first used to model vacuum-tube oscillator circuits, but it has been used in other applications such as the modeling of pulsating stars called Cephids. A code for the Van der Pol equation is RM11OM9KM2KM6OM28.
	Such limit cycles are characterized by a dimension of one and a Lyapunov exponent of zero. The dimension as approximated by the program will usually not be exactly 1.0 for the reasons discussed in Section 3.4. The Lyapunov exponent is a much better criterion for identifying limit cycles. In a two-dimensional embedding space, as in the previous examples, there are two Lyapunov exponents. The smaller (more negative) of them is the rate at which trajectories with different initial conditions approach the attractor. The larger exponent (the one calculated by the program) is the rate at which two nearby points on the limit cycle separate. For a limit cycle produced by ODEs, this exponent must be zero because points along the trajectory are governed by the same rates of flow, except delayed in time.
	In two dimensions, the limit cycles cannot cross, so the most complicated shapes are simple distorted loops. In three or more dimensions, they can wrap around in a complicated tangle like a ball of string, but without ends. Figures 6-43 through 6-50 show a collection of visually interesting limit cycles. They are plotted as stereo pairs so that you can see how the trajectories pass beneath one another.

Figure 6-43. Limit cycle from a three-dimensional quadratic map

Figure 6-44. Limit cycle from a three-dimensional quadratic ODE

Figure 6-45. Limit cycle from three-dimensional quadratic ODE

Figure 6-46. Limit cycle from a three-dimensional quadratic ODE

Figure 6-47. Limit cycle from a three-dimensional cubic ODE

Figure 6-48. Limit cycle from a three-dimensional quintic ODE

Figure 6-49. Limit cycle from a four-dimensional quadratic ODE

Figure 6-50. Limit cycle from a four-dimensional quartic ODE

	As you examine the figures, note that some of the limit cycles, such as the one in Figure 6-43, form knots. You cannot straighten them out into circular loops. By contrast, Figure 6-47 is unknotted. This knottedness or helicity is an important topological property of an attractor. Some processes in nature tend to conserve helicity, just as mechanical energy is conserved in frictionless motion. Thus when some parameter of the system is changed, the limit cycle may change its size and shape but in such a way that it always links itself in the same way. An example is a magnetic field line in a turbulent conducting fluid such as a plasma of electrically charged particles.
	For many of the limit cycles exhibited here, it is very hard to tell whether they are knotted. Even when they appear to be knotted, it is hard to tell whether two cases are knotted in the same way. Such patterns might provide a useful psychological test for one’s spatial acuity because they require both depth perception and a mental dexterity to visualize their shape when untangled as much as possible. See which of the limit cycles in the figures you think are knotted.


##  Doughnuts and Coffee Cups
	Non-chaotic attractors can be points or lines. They can also be surfaces. Surfaces are two-dimensional manifolds. Perhaps the simplest set of equations whose solution is a trajectory that fills a surface is the following:
	
	X’ = Y
	Y’ = -X
	Z’ = aW
	W’ = -Z							(Equation 6J)

You will recognize the first two equations as the same as Equation 6A that produces a circle in the XY plane. The second two equations produce an ellipse in the ZW plane. The two motions are uncoupled (X and Y don’t depend on Z or W; Z and W don’t depend on X or Y). The parameter a is the square of the angular frequency of the second motion. If the square root of a is a rational number (a ratio of two integers) the trajectory is a closed one-dimensional loop in the four-dimensional embedding space.
	If the square root of a is irrational, the trajectory fills a two-dimensional toroidal surface (called a 2-torus). The trajectory winds endlessly around the surface of a dougnut, never intersecting itself. In such a case we say the frequencies (the number of transits per second the long way around and the short way around) are incommensurate and that the trajectory is quasi-periodic. The sequence never repeats, but it is not chaotic. It is sometimes difficult to distinguish between quasi-periodic and chaotic behavior.
	A useful tool for distinguishing between a quasi-periodic and a chaotic attractor is the power spectrum of the time series, which has sharp peaks at discrete frequencies for quasi-periodic trajectories but a broad (continuous) spectrum for chaotic trajectories. The power spectrum contains about half of the information required to reconstruct the trajectory; the frequency information is present, but the phase information is lost. Nevertheless, the power spectrum serves as a kind of fingerprint that is very useful in categorizing attractors.
	The equation set in Equation 6J has the same problems as Equation 6A. They don’t represent an attractor because nearly all initial conditions produce different tori. Furthermore, the tori produced in this way are structurally unstable, just like the circles of Equation 6A. These difficulties can be circumvented by using instead an extension of Equations 6H to produce two uncoupled limit cycles as follows:

	X’ = Y + (1 - X2 - Y2)X
	Y’ = -X + (1 - X2 - Y2)Y
	Z = aW + (1 - Z2 - W2)Z
	W = -Z + (1 - Z2 - W2)W				(Equation 6K)

A value of a = 2 provides an acceptable irrational frequency ratio, because the square root of 2 cannot be represented as a ratio of two integers. The corresponding trajectory can be generated using the code VMNMAM4AM7NM19LM2-AM11NMAM42NMAM2AOM28LM2AM2NMA. A rotated version of the 2-torus in which one loop is in the XZ plane and the other is in the YW plane is produced by the code VMNMAM8AM13NM24NMAM6AM6OM3LM3AM20NMAM22L-M3AM11NMA.
	Two uncoupled limit cycles lie on a torus that is attractive, but it is not technically an attractor; it is called an invariant manifold. For an object to be an attractor, it must not only attract nearby trajectories, but most trajectories on it must wander all over it, in which case we say the set is transitive and the orbits are ergodic. Ergodic orbits produce mixing, which means that an orbit starting from anywhere on the attractor eventually comes arbitrarily close to every other point on the attractor. Mixing ensures that an attractor cannot be split into two different attractors, although the attractor need not be connected. Figure 5-11 shows an attractor that is not connected. Thus not all attractive tori are attractors, just as not all attractors are tori.
	Tori can be identified in the computer search by a Lyapunov exponent close to zero and a dimension well above one. It is easy to distinguish them visually from limit cycles, which also have Lyapunov exponents close to zero but resemble lines rather than surfaces. A selection of tori projected onto the XY plane is shown in Figures 6-51 through 6-60.

Figure 6-51. Torus from a three-dimensional cubic ODE

Figure 6-52. Torus from Three-Dimensional Cubic ODE

Figure 6-53. Torus from a four-dimensional quadratic ODE

Figure 6-54. Torus from a four-dimensional quadratic ODE

Figure 6-55. Torus from a four-dimensional quadratic ODE

Figure 6-56. Torus from a four-dimensional quadratic ODE

Figure 6-57. Torus from a four-dimensional quadratic ODE

Figure 6-58. Torus from a four-dimensional quadratic ODE

Figure 6-59. Torus from a four-dimensional cubic ODE

Figure 6-60. Torus from a four-dimensional quartic ODE

	Most of the attractors shown in the figures look like tori in the sense that you can see or imagine the hole in the doughnut. However, it is important to understand that, just as not all limit cycles are circles, not all 2-tori look like doughnuts. They are topologically equivalent in the sense that there is a “rubber-sheet” deformation (called a homeomorphism) that maps them into a doughnut. A coffee cup, for example, is topologically equivalent to a doughnut as long as the handle is unbroken.
	Those cases that are not obviously equivalent to a simple torus are distorted by the fact that they are viewed projected onto the XY plane or because they are rotated at an awkward angle. Also note that most of these tori are embedded in a four-dimensional space, so it is even more difficult to grasp their shape from a two-dimensional projection. You might want to display them using some of the advanced visualization techniques provided by the program.
	It is possible, though difficult, to produce a 3-torus in a four-dimensional embedding space. A 3-torus is a generalization of a 2-torus. It is hard to visualize. It involves three mutually incommensurate frequencies. It is characterized by a dimension of three and a largest Lyapunov exponent of zero. Some of the attractors in the figures seem to be 3-tori according to their calculated dimension. However, the calculation is not sufficiently precise to distinguish unambiguously between a 2-torus and a 3-torus. It is necessary to search embedding dimensions greater than four to have a good chance of finding 3-tori.
	Dynamical systems whose trajectories lie on a 3-torus or other hypertori of even higher dimensions are difficult to observe in nature. The reason is that such attractors can be perturbed by an arbitrarily small change to the system that causes them to become strange attractors. According to Peixoto’s theorem (which strictly applies only to compact, orientable manifolds), 2-tori tend to be structurally stable, while 3-tori and higher are structurally unstable. Thus it appears that complicated deterministic systems that exhibit nontrivial behavior are well represented by the strange attractors that constitute the subject of this book.
