--- 
title: "Strange Attractors"
author: " Julien C. Sprott"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Why This Book Is For You

Art and science sometimes appear in juxtaposition, one aesthetic, the other
analytical. This book bridges the two cultures. I have written it for the artist who is willing to devote a modicum of effort to understanding the mathematical world of the scientist and for the scientist who often overlooks the beauty that lurks just beneath even the simplest equations.

If you are neither artist nor scientist, but own a personal computer for which you would like to find an exciting new use, this book is also for you. Fractals generated by computer represent a new art form that anyone can appreciate and appropriate. You don’t have to know mathematics beyond elementary algebra, and you don’t have to be an expert programmer. This book explains a simple, new technique for generating a class of fractals called strange attractors. Unlike other books about fractals that teach you to reproduce well-known patterns, this one will let you produce your own unlimited variety of displays and musical sounds with a single program. Almost none of the patterns you produce will ever have been seen before.

To get the most out of this book, you will need a personal computer, though it need not be a fancy one. It should have a monitor capable of displaying graphics, preferably in color. Some knowledge of BASIC is useful, although you can just type in the listings even if you don’t understand them completely. For those of you who are C programmers, I have provided an appendix with an equivalent version in C. You may find the exercises in this book an enjoyable way to hone your programming skills. As you progress through the book, you will gradually develop a very sophisticated computer program. Each step is relatively simple and brings exciting new things to see and explore. Alternately, you can use the accompanying disk immediately to begin making your own collection of strange attractors.